import {
  Building2,
  FileText,
  Route,
  CalendarClock,
  Boxes,
  ClipboardCheck,
  GanttChartSquare,
  Users,
  Timer,
  Wallet,
  SearchCheck,
  ShieldAlert,
  Lightbulb,
  PencilRuler,
  Box,
  FileCheck2,
  Palette,
  GitMerge,
  Gem,
  Layers3,
  Hammer,
  Lamp,
  Bath,
  Paintbrush,
} from 'lucide-react';
import type { LocalizedServiceConfig } from './ServicePage';

export const ENGINEERING: LocalizedServiceConfig = {
  en: {
    label: 'Engineering',
    title: 'Engineering Excellence for Complex Projects',
    accent: 'Excellence',
    subtitle:
      'SOCODECO provides integrated engineering solutions that combine technical precision, structural expertise and practical construction knowledge.',
    heroVideo: '/expertise-engineering.mp4',
    heroPoster: '/expertise-engineering.jpg',
    introHeading: 'Where Structures Are',
    introAccent: 'Solved',
    introText: [
      'Our engineering team turns architectural ambition into buildable reality. Structures, methods and networks are calculated, coordinated and documented before the first excavator arrives on site.',
      'Because our engineers work beside our own construction crews in Kinshasa, every study is grounded in what can actually be built — on this soil, with this grid, on this schedule.',
    ],
    introImg: '/expertise-engineering.jpg',
    introImgAlt: 'SOCODECO engineer drafting column reinforcement details at golden hour',
    services: [
      { icon: Building2, title: 'Structural Engineering', text: 'Concrete and steel structures calculated for Kinshasa soil and seismic reality.' },
      { icon: FileText, title: 'Technical Studies', text: 'Geotechnical, electrical and hydraulic studies documented and verifiable.' },
      { icon: Route, title: 'Method Engineering', text: 'Execution methods, phasing and formwork strategies that keep sites moving.' },
      { icon: CalendarClock, title: 'Construction Planning', text: 'Realistic sequencing and resource plans tied to procurement realities.' },
      { icon: Boxes, title: 'BIM Coordination', text: 'One coordinated 3D model — clashes resolved on screen, not on the slab.' },
      { icon: ClipboardCheck, title: 'Quality Control', text: 'Materials tested, works inspected and every phase signed before closure.' },
    ],
    steps: [
      { n: '01', title: 'Technical Analysis' },
      { n: '02', title: 'Structural Design' },
      { n: '03', title: 'Studies & Calculations' },
      { n: '04', title: 'Methods & Planning' },
      { n: '05', title: 'Site Validation' },
    ],
    filmVideo: '/hero-journey.mp4',
    filmPoster: '/hero-journey-poster.jpg',
    filmHeading: 'Calculation becomes',
    filmAccent: 'concrete.',
    filmText: 'Every SOCODECO structure begins as a verified calculation — and ends as a landmark above Kinshasa.',
    ctaBg: '/construction-cta.jpg',
  },
  fr: {
    label: 'Ingénierie',
    title: "L'Excellence de l'ingénierie pour des projets complexes",
    accent: 'Excellence',
    subtitle:
      "SOCODECO fournit des solutions d'ingénierie intégrées qui allient précision technique, expertise structurelle et connaissance concrète du chantier.",
    heroVideo: '/expertise-engineering.mp4',
    heroPoster: '/expertise-engineering.jpg',
    introHeading: 'Là où les structures sont',
    introAccent: 'résolues',
    introText: [
      "Notre équipe d'ingénierie transforme l'ambition architecturale en réalité constructible. Structures, méthodes et réseaux sont calculés, coordonnés et documentés avant l'arrivée du premier engin sur site.",
      'Parce que nos ingénieurs travaillent aux côtés de nos propres équipes de construction à Kinshasa, chaque étude est ancrée dans ce qui peut réellement être construit — sur ce sol, avec ce réseau, dans ces délais.',
    ],
    introImg: '/expertise-engineering.jpg',
    introImgAlt: "Ingénieur SOCODECO dessinant des détails de ferraillage de colonne à l'heure dorée",
    services: [
      { icon: Building2, title: 'Ingénierie structurelle', text: 'Structures en béton et en acier calculées pour le sol et la réalité sismique de Kinshasa.' },
      { icon: FileText, title: 'Études techniques', text: 'Études géotechniques, électriques et hydrauliques documentées et vérifiables.' },
      { icon: Route, title: 'Ingénierie des méthodes', text: "Méthodes d'exécution, phasage et stratégies de coffrage qui font avancer les chantiers." },
      { icon: CalendarClock, title: 'Planification des travaux', text: "Séquencement réaliste et plans de ressources liés aux réalités d'approvisionnement." },
      { icon: Boxes, title: 'Coordination BIM', text: "Un seul modèle 3D coordonné — les conflits résolus à l'écran, pas sur la dalle." },
      { icon: ClipboardCheck, title: 'Contrôle qualité', text: 'Matériaux testés, ouvrages inspectés et chaque phase signée avant clôture.' },
    ],
    steps: [
      { n: '01', title: 'Analyse technique' },
      { n: '02', title: 'Conception structurelle' },
      { n: '03', title: 'Études & calculs' },
      { n: '04', title: 'Méthodes & planification' },
      { n: '05', title: 'Validation sur site' },
    ],
    filmVideo: '/hero-journey.mp4',
    filmPoster: '/hero-journey-poster.jpg',
    filmHeading: 'Le calcul devient',
    filmAccent: 'béton.',
    filmText: "Chaque structure SOCODECO naît d'un calcul vérifié — et s'achève en édifice emblématique au-dessus de Kinshasa.",
    ctaBg: '/construction-cta.jpg',
  },
};

export const MANAGEMENT: LocalizedServiceConfig = {
  en: {
    label: 'Project Management',
    title: 'Managing Every Detail from Concept to Delivery',
    accent: 'Every Detail',
    subtitle:
      'SOCODECO plans, coordinates and supervises every stage of construction to ensure quality, safety, cost control and on-time delivery.',
    heroVideo: '/expertise-management.mp4',
    heroPoster: '/expertise-management.jpg',
    introHeading: 'One Team, One',
    introAccent: 'Accountability',
    introText: [
      'A project succeeds when someone answers for the whole — schedule, cost, quality and safety together. Our project managers carry that responsibility from the first meeting to the final handover.',
      'Weekly reporting, open books and digital site monitoring keep owners informed without leaving their office, while our supervisors keep every trade aligned on site in Kinshasa.',
    ],
    introImg: '/expertise-management.jpg',
    introImgAlt: 'SOCODECO engineer running a digital site inspection checklist against rebar walls',
    services: [
      { icon: GanttChartSquare, title: 'Project Planning', text: 'Scope, budget and master schedule locked before mobilization.' },
      { icon: Users, title: 'Site Coordination', text: 'Every trade sequenced and supervised by one accountable team.' },
      { icon: Timer, title: 'Schedule Management', text: 'Progress measured weekly against the plan — drift caught early.' },
      { icon: Wallet, title: 'Cost Control', text: 'Open books, verified quantities and no surprise variations.' },
      { icon: SearchCheck, title: 'Quality Supervision', text: 'Inspections and sign-offs at every milestone, documented for the owner.' },
      { icon: ShieldAlert, title: 'Safety Management', text: 'Zero-incident policy enforced daily — PPE, permits and audits.' },
    ],
    steps: [
      { n: '01', title: 'Project Planning' },
      { n: '02', title: 'Mobilization' },
      { n: '03', title: 'Coordination' },
      { n: '04', title: 'Monitoring & Control' },
      { n: '05', title: 'Handover' },
    ],
    filmVideo: '/about-hero.mp4',
    filmPoster: '/about-hero-poster.jpg',
    filmHeading: 'Supervised at',
    filmAccent: 'sunrise.',
    filmText: 'Our project directors walk the site before the city wakes — so owners never have to wonder.',
    ctaBg: '/realestate-cta.jpg',
  },
  fr: {
    label: 'Gestion de projet',
    title: 'Gérer Chaque Détail, du concept à la livraison',
    accent: 'Chaque Détail',
    subtitle:
      'SOCODECO planifie, coordonne et supervise chaque étape de la construction pour garantir la qualité, la sécurité, la maîtrise des coûts et la livraison dans les délais.',
    heroVideo: '/expertise-management.mp4',
    heroPoster: '/expertise-management.jpg',
    introHeading: 'Une équipe, une seule',
    introAccent: 'responsabilité',
    introText: [
      "Un projet réussit lorsque quelqu'un répond de l'ensemble — planning, coûts, qualité et sécurité réunis. Nos chefs de projet portent cette responsabilité de la première réunion à la remise finale des clés.",
      "Rapports hebdomadaires, comptes ouverts et suivi numérique du chantier tiennent les maîtres d'ouvrage informés sans quitter leur bureau, pendant que nos superviseurs alignent chaque corps de métier sur site à Kinshasa.",
    ],
    introImg: '/expertise-management.jpg',
    introImgAlt: 'Ingénieur SOCODECO effectuant une inspection numérique du chantier devant des voiles de ferraillage',
    services: [
      { icon: GanttChartSquare, title: 'Planification de projet', text: 'Périmètre, budget et planning directeur verrouillés avant la mobilisation.' },
      { icon: Users, title: 'Coordination de chantier', text: 'Chaque corps de métier séquencé et supervisé par une seule équipe responsable.' },
      { icon: Timer, title: 'Gestion du planning', text: "L'avancement mesuré chaque semaine par rapport au plan — les dérives détectées tôt." },
      { icon: Wallet, title: 'Maîtrise des coûts', text: 'Comptes ouverts, quantités vérifiées et aucun avenant surprise.' },
      { icon: SearchCheck, title: 'Supervision qualité', text: "Inspections et validations à chaque jalon, documentées pour le maître d'ouvrage." },
      { icon: ShieldAlert, title: 'Gestion de la sécurité', text: 'Politique zéro incident appliquée au quotidien — EPI, permis et audits.' },
    ],
    steps: [
      { n: '01', title: 'Planification' },
      { n: '02', title: 'Mobilisation' },
      { n: '03', title: 'Coordination' },
      { n: '04', title: 'Suivi & contrôle' },
      { n: '05', title: 'Remise des clés' },
    ],
    filmVideo: '/about-hero.mp4',
    filmPoster: '/about-hero-poster.jpg',
    filmHeading: 'Supervisé au',
    filmAccent: 'lever du soleil.',
    filmText: "Nos directeurs de projet parcourent le chantier avant le réveil de la ville — pour que les maîtres d'ouvrage n'aient jamais à s'inquiéter.",
    ctaBg: '/realestate-cta.jpg',
  },
};

export const ARCHITECTURE: LocalizedServiceConfig = {
  en: {
    label: 'Architecture',
    title: 'Designing Spaces with Vision and Precision',
    accent: 'Vision',
    subtitle:
      'SOCODECO creates architectural solutions that combine functionality, elegance and long-term value for residential, commercial and institutional projects.',
    heroVideo: '/expertise-architecture.mp4',
    heroPoster: '/expertise-architecture.jpg',
    introHeading: 'Designed to Be',
    introAccent: 'Built',
    introText: [
      'Our Lebanese and Congolese architects design together in Kinshasa — shaping residences, offices and institutions that belong to their street, their climate and their people.',
      'Because the same house engineers and builds what it draws, every concept is tested against structure, budget and buildability before it reaches your desk.',
    ],
    introImg: '/expertise-architecture.jpg',
    introImgAlt: 'SOCODECO architects reviewing physical scale models in the Kinshasa design studio',
    services: [
      { icon: Lightbulb, title: 'Concept Design', text: 'Ideas grounded in site, program and Congolese urban life.' },
      { icon: PencilRuler, title: 'Architectural Plans', text: 'Complete, coordinated drawing sets ready for permit and site.' },
      { icon: Box, title: '3D Visualization', text: 'Photorealistic renderings and models — decisions made with open eyes.' },
      { icon: FileCheck2, title: 'Permit Documentation', text: 'Urbanism and regulatory files handled from submission to approval.' },
      { icon: Palette, title: 'Material Selection', text: 'Facades and finishes sampled, benchmarked and approved with you.' },
      { icon: GitMerge, title: 'Design Coordination', text: 'Architecture, structure and services resolved in one model.' },
    ],
    steps: [
      { n: '01', title: 'Brief & Concept' },
      { n: '02', title: 'Design Development' },
      { n: '03', title: 'Visualization' },
      { n: '04', title: 'Permits' },
      { n: '05', title: 'Construction Support' },
    ],
    filmVideo: '/expertise-realestate.mp4',
    filmPoster: '/expertise-realestate.jpg',
    filmHeading: 'From sketch to',
    filmAccent: 'skyline.',
    filmText: 'The developments our studio draws become the places Kinshasa is proud of.',
    ctaBg: '/realestate-cta.jpg',
  },
  fr: {
    label: 'Architecture',
    title: 'Concevoir des espaces avec Vision et Précision',
    accent: 'Vision',
    subtitle:
      'SOCODECO crée des solutions architecturales qui allient fonctionnalité, élégance et valeur à long terme pour des projets résidentiels, commerciaux et institutionnels.',
    heroVideo: '/expertise-architecture.mp4',
    heroPoster: '/expertise-architecture.jpg',
    introHeading: 'Conçu pour être',
    introAccent: 'construit',
    introText: [
      'Nos architectes libanais et congolais conçoivent ensemble à Kinshasa — façonnant des résidences, des bureaux et des institutions qui appartiennent à leur rue, à leur climat et à leurs habitants.',
      "Parce que la même maison calcule et construit ce qu'elle dessine, chaque concept est confronté à la structure, au budget et à la constructibilité avant d'arriver sur votre bureau.",
    ],
    introImg: '/expertise-architecture.jpg',
    introImgAlt: 'Architectes SOCODECO examinant des maquettes physiques dans le studio de conception de Kinshasa',
    services: [
      { icon: Lightbulb, title: 'Conception', text: 'Des idées ancrées dans le site, le programme et la vie urbaine congolaise.' },
      { icon: PencilRuler, title: "Plans d'architecture", text: 'Des dossiers de plans complets et coordonnés, prêts pour le permis et le chantier.' },
      { icon: Box, title: 'Visualisation 3D', text: 'Rendus photoréalistes et maquettes — des décisions prises en toute connaissance.' },
      { icon: FileCheck2, title: 'Dossiers de permis', text: "Dossiers d'urbanisme et réglementaires gérés du dépôt à l'approbation." },
      { icon: Palette, title: 'Sélection des matériaux', text: 'Façades et finitions échantillonnées, comparées et approuvées avec vous.' },
      { icon: GitMerge, title: 'Coordination de conception', text: 'Architecture, structure et réseaux résolus dans un seul modèle.' },
    ],
    steps: [
      { n: '01', title: 'Brief & concept' },
      { n: '02', title: 'Développement du design' },
      { n: '03', title: 'Visualisation' },
      { n: '04', title: 'Permis' },
      { n: '05', title: 'Suivi de chantier' },
    ],
    filmVideo: '/expertise-realestate.mp4',
    filmPoster: '/expertise-realestate.jpg',
    filmHeading: 'Du croquis à',
    filmAccent: "l'horizon.",
    filmText: 'Les projets que notre studio dessine deviennent les lieux dont Kinshasa est fière.',
    ctaBg: '/realestate-cta.jpg',
  },
};

export const INTERIOR: LocalizedServiceConfig = {
  en: {
    label: 'Interior Finishing',
    title: 'Luxury Finishes Crafted with Detail and Precision',
    accent: 'Detail',
    subtitle:
      'SOCODECO delivers refined interior spaces through premium materials, expert craftsmanship and complete finishing coordination.',
    heroVideo: '/expertise-interior.mp4',
    heroPoster: '/expertise-interior.jpg',
    introHeading: 'The Last 5% Is',
    introAccent: 'Everything',
    introText: [
      'A building is judged by what the hand touches and the eye rests on. Our finishing teams bring marble, wood, gypsum and light together with the patience luxury demands.',
      'From material sampling to the final styling walk-through, one coordinator answers for every finish in the space — in your apartment, office or hotel in Kinshasa.',
    ],
    introImg: '/expertise-interior.jpg',
    introImgAlt: 'SOCODECO craftsman installing book-matched marble in a luxury Kinshasa apartment',
    services: [
      { icon: Gem, title: 'Marble and Flooring', text: 'Book-matched stone and precision flooring laid to millimetric joints.' },
      { icon: Layers3, title: 'Gypsum Ceilings', text: 'Curved profiles and shadow gaps with integrated cove lighting.' },
      { icon: Hammer, title: 'Custom Woodwork', text: 'Walnut joinery, doors and wardrobes made to drawing.' },
      { icon: Lamp, title: 'Lighting Installation', text: 'Layered lighting scenes that flatter material and mood.' },
      { icon: Bath, title: 'Luxury Bathrooms', text: 'Stone, brass and glass assembled to hotel standard.' },
      { icon: Paintbrush, title: 'Painting and Decoration', text: 'Flawless final coats and styling down to the last detail.' },
    ],
    steps: [
      { n: '01', title: 'Design & Materials' },
      { n: '02', title: 'Sampling & Approval' },
      { n: '03', title: 'Execution' },
      { n: '04', title: 'Detailing' },
      { n: '05', title: 'Styling & Handover' },
    ],
    filmVideo: '/realestate-invest.mp4',
    filmPoster: '/realestate-invest.jpg',
    filmHeading: 'Finished for the',
    filmAccent: 'evening light.',
    filmText: 'Interiors that come alive when the sun sets over Kinshasa — warm, layered and lived in.',
    ctaBg: '/construction-cta.jpg',
  },
  fr: {
    label: 'Finitions intérieures',
    title: 'Des finitions de luxe façonnées avec Détail et Précision',
    accent: 'Détail',
    subtitle:
      'SOCODECO livre des espaces intérieurs raffinés grâce à des matériaux haut de gamme, un artisanat expert et une coordination complète des finitions.',
    heroVideo: '/expertise-interior.mp4',
    heroPoster: '/expertise-interior.jpg',
    introHeading: "Les derniers 5 %, c'est",
    introAccent: 'tout',
    introText: [
      "Un bâtiment se juge à ce que la main touche et à ce sur quoi l'œil se pose. Nos équipes de finition réunissent marbre, bois, gypse et lumière avec la patience que le luxe exige.",
      "De l'échantillonnage des matériaux à la visite finale de mise en scène, un seul coordinateur répond de chaque finition de l'espace — dans votre appartement, votre bureau ou votre hôtel à Kinshasa.",
    ],
    introImg: '/expertise-interior.jpg',
    introImgAlt: 'Artisan SOCODECO posant du marbre book-match dans un appartement de luxe à Kinshasa',
    services: [
      { icon: Gem, title: 'Marbre et revêtements de sol', text: 'Pierre book-match et sols de précision posés au joint millimétrique.' },
      { icon: Layers3, title: 'Plafonds en gypse', text: 'Profils courbes et joints creux avec éclairage indirect intégré.' },
      { icon: Hammer, title: 'Menuiserie sur mesure', text: 'Menuiseries en noyer, portes et dressings réalisés au plan.' },
      { icon: Lamp, title: "Installation d'éclairage", text: 'Des scènes lumineuses en couches qui subliment matière et ambiance.' },
      { icon: Bath, title: 'Salles de bain de luxe', text: 'Pierre, laiton et verre assemblés au standard hôtelier.' },
      { icon: Paintbrush, title: 'Peinture et décoration', text: "Couches finales impeccables et mise en scène jusqu'au dernier détail." },
    ],
    steps: [
      { n: '01', title: 'Design & matériaux' },
      { n: '02', title: 'Échantillonnage & validation' },
      { n: '03', title: 'Exécution' },
      { n: '04', title: 'Détails' },
      { n: '05', title: 'Mise en scène & remise' },
    ],
    filmVideo: '/realestate-invest.mp4',
    filmPoster: '/realestate-invest.jpg',
    filmHeading: 'Finis pour la',
    filmAccent: 'lumière du soir.',
    filmText: "Des intérieurs qui s'animent quand le soleil se couche sur Kinshasa — chaleureux, texturés et habités.",
    ctaBg: '/construction-cta.jpg',
  },
};
