import {
  Building2,
  FileText,
  Route,
  CalendarClock,
  Boxes,
  ClipboardCheck,
  GanttChartSquare,
  Users,
  Timer,
  Wallet,
  SearchCheck,
  ShieldAlert,
  Lightbulb,
  PencilRuler,
  Box,
  FileCheck2,
  Palette,
  GitMerge,
  Gem,
  Layers3,
  Hammer,
  Lamp,
  Bath,
  Paintbrush,
} from 'lucide-react';
import type { ServiceConfig } from './ServicePage';

export const ENGINEERING: ServiceConfig = {
  label: 'Engineering',
  title: 'Engineering Excellence for Complex Projects',
  accent: 'Excellence',
  subtitle:
    'SOCODECO provides integrated engineering solutions that combine technical precision, structural expertise and practical construction knowledge.',
  heroVideo: '/expertise-engineering.mp4',
  heroPoster: '/expertise-engineering.jpg',
  introHeading: 'Where Structures Are',
  introAccent: 'Solved',
  introText: [
    'Our engineering team turns architectural ambition into buildable reality. Structures, methods and networks are calculated, coordinated and documented before the first excavator arrives on site.',
    'Because our engineers work beside our own construction crews in Kinshasa, every study is grounded in what can actually be built — on this soil, with this grid, on this schedule.',
  ],
  introImg: '/expertise-engineering.jpg',
  introImgAlt: 'SOCODECO engineer drafting column reinforcement details at golden hour',
  services: [
    { icon: Building2, title: 'Structural Engineering', text: 'Concrete and steel structures calculated for Kinshasa soil and seismic reality.' },
    { icon: FileText, title: 'Technical Studies', text: 'Geotechnical, electrical and hydraulic studies documented and verifiable.' },
    { icon: Route, title: 'Method Engineering', text: 'Execution methods, phasing and formwork strategies that keep sites moving.' },
    { icon: CalendarClock, title: 'Construction Planning', text: 'Realistic sequencing and resource plans tied to procurement realities.' },
    { icon: Boxes, title: 'BIM Coordination', text: 'One coordinated 3D model — clashes resolved on screen, not on the slab.' },
    { icon: ClipboardCheck, title: 'Quality Control', text: 'Materials tested, works inspected and every phase signed before closure.' },
  ],
  steps: [
    { n: '01', title: 'Technical Analysis' },
    { n: '02', title: 'Structural Design' },
    { n: '03', title: 'Studies & Calculations' },
    { n: '04', title: 'Methods & Planning' },
    { n: '05', title: 'Site Validation' },
  ],
  filmVideo: '/hero-journey.mp4',
  filmPoster: '/hero-journey-poster.jpg',
  filmHeading: 'Calculation becomes',
  filmAccent: 'concrete.',
  filmText: 'Every SOCODECO structure begins as a verified calculation — and ends as a landmark above Kinshasa.',
  ctaBg: '/construction-cta.jpg',
};

export const MANAGEMENT: ServiceConfig = {
  label: 'Project Management',
  title: 'Managing Every Detail from Concept to Delivery',
  accent: 'Every Detail',
  subtitle:
    'SOCODECO plans, coordinates and supervises every stage of construction to ensure quality, safety, cost control and on-time delivery.',
  heroVideo: '/expertise-management.mp4',
  heroPoster: '/expertise-management.jpg',
  introHeading: 'One Team, One',
  introAccent: 'Accountability',
  introText: [
    'A project succeeds when someone answers for the whole — schedule, cost, quality and safety together. Our project managers carry that responsibility from the first meeting to the final handover.',
    'Weekly reporting, open books and digital site monitoring keep owners informed without leaving their office, while our supervisors keep every trade aligned on site in Kinshasa.',
  ],
  introImg: '/expertise-management.jpg',
  introImgAlt: 'SOCODECO engineer running a digital site inspection checklist against rebar walls',
  services: [
    { icon: GanttChartSquare, title: 'Project Planning', text: 'Scope, budget and master schedule locked before mobilization.' },
    { icon: Users, title: 'Site Coordination', text: 'Every trade sequenced and supervised by one accountable team.' },
    { icon: Timer, title: 'Schedule Management', text: 'Progress measured weekly against the plan — drift caught early.' },
    { icon: Wallet, title: 'Cost Control', text: 'Open books, verified quantities and no surprise variations.' },
    { icon: SearchCheck, title: 'Quality Supervision', text: 'Inspections and sign-offs at every milestone, documented for the owner.' },
    { icon: ShieldAlert, title: 'Safety Management', text: 'Zero-incident policy enforced daily — PPE, permits and audits.' },
  ],
  steps: [
    { n: '01', title: 'Project Planning' },
    { n: '02', title: 'Mobilization' },
    { n: '03', title: 'Coordination' },
    { n: '04', title: 'Monitoring & Control' },
    { n: '05', title: 'Handover' },
  ],
  filmVideo: '/about-hero.mp4',
  filmPoster: '/about-hero-poster.jpg',
  filmHeading: 'Supervised at',
  filmAccent: 'sunrise.',
  filmText: 'Our project directors walk the site before the city wakes — so owners never have to wonder.',
  ctaBg: '/realestate-cta.jpg',
};

export const ARCHITECTURE: ServiceConfig = {
  label: 'Architecture',
  title: 'Designing Spaces with Vision and Precision',
  accent: 'Vision',
  subtitle:
    'SOCODECO creates architectural solutions that combine functionality, elegance and long-term value for residential, commercial and institutional projects.',
  heroVideo: '/expertise-architecture.mp4',
  heroPoster: '/expertise-architecture.jpg',
  introHeading: 'Designed to Be',
  introAccent: 'Built',
  introText: [
    'Our Lebanese and Congolese architects design together in Kinshasa — shaping residences, offices and institutions that belong to their street, their climate and their people.',
    'Because the same house engineers and builds what it draws, every concept is tested against structure, budget and buildability before it reaches your desk.',
  ],
  introImg: '/expertise-architecture.jpg',
  introImgAlt: 'SOCODECO architects reviewing physical scale models in the Kinshasa design studio',
  services: [
    { icon: Lightbulb, title: 'Concept Design', text: 'Ideas grounded in site, program and Congolese urban life.' },
    { icon: PencilRuler, title: 'Architectural Plans', text: 'Complete, coordinated drawing sets ready for permit and site.' },
    { icon: Box, title: '3D Visualization', text: 'Photorealistic renderings and models — decisions made with open eyes.' },
    { icon: FileCheck2, title: 'Permit Documentation', text: 'Urbanism and regulatory files handled from submission to approval.' },
    { icon: Palette, title: 'Material Selection', text: 'Facades and finishes sampled, benchmarked and approved with you.' },
    { icon: GitMerge, title: 'Design Coordination', text: 'Architecture, structure and services resolved in one model.' },
  ],
  steps: [
    { n: '01', title: 'Brief & Concept' },
    { n: '02', title: 'Design Development' },
    { n: '03', title: 'Visualization' },
    { n: '04', title: 'Permits' },
    { n: '05', title: 'Construction Support' },
  ],
  filmVideo: '/expertise-realestate.mp4',
  filmPoster: '/expertise-realestate.jpg',
  filmHeading: 'From sketch to',
  filmAccent: 'skyline.',
  filmText: 'The developments our studio draws become the places Kinshasa is proud of.',
  ctaBg: '/realestate-cta.jpg',
};

export const INTERIOR: ServiceConfig = {
  label: 'Interior Finishing',
  title: 'Luxury Finishes Crafted with Detail and Precision',
  accent: 'Detail',
  subtitle:
    'SOCODECO delivers refined interior spaces through premium materials, expert craftsmanship and complete finishing coordination.',
  heroVideo: '/expertise-interior.mp4',
  heroPoster: '/expertise-interior.jpg',
  introHeading: 'The Last 5% Is',
  introAccent: 'Everything',
  introText: [
    'A building is judged by what the hand touches and the eye rests on. Our finishing teams bring marble, wood, gypsum and light together with the patience luxury demands.',
    'From material sampling to the final styling walk-through, one coordinator answers for every finish in the space — in your apartment, office or hotel in Kinshasa.',
  ],
  introImg: '/expertise-interior.jpg',
  introImgAlt: 'SOCODECO craftsman installing book-matched marble in a luxury Kinshasa apartment',
  services: [
    { icon: Gem, title: 'Marble and Flooring', text: 'Book-matched stone and precision flooring laid to millimetric joints.' },
    { icon: Layers3, title: 'Gypsum Ceilings', text: 'Curved profiles and shadow gaps with integrated cove lighting.' },
    { icon: Hammer, title: 'Custom Woodwork', text: 'Walnut joinery, doors and wardrobes made to drawing.' },
    { icon: Lamp, title: 'Lighting Installation', text: 'Layered lighting scenes that flatter material and mood.' },
    { icon: Bath, title: 'Luxury Bathrooms', text: 'Stone, brass and glass assembled to hotel standard.' },
    { icon: Paintbrush, title: 'Painting and Decoration', text: 'Flawless final coats and styling down to the last detail.' },
  ],
  steps: [
    { n: '01', title: 'Design & Materials' },
    { n: '02', title: 'Sampling & Approval' },
    { n: '03', title: 'Execution' },
    { n: '04', title: 'Detailing' },
    { n: '05', title: 'Styling & Handover' },
  ],
  filmVideo: '/realestate-invest.mp4',
  filmPoster: '/realestate-invest.jpg',
  filmHeading: 'Finished for the',
  filmAccent: 'evening light.',
  filmText: 'Interiors that come alive when the sun sets over Kinshasa — warm, layered and lived in.',
  ctaBg: '/construction-cta.jpg',
};
